Traceback (most recent call last):
  File "/home/slava/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/slava/.local/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/slava/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/slava/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/slava/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/slava/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# –û–ø—Ä–µ–¥–µ–ª—è–µ–º –≥—Ä–∞—Ñ–∏–∫ Y –æ—Ç X
plt.plot(X, Y, 'o', label="–ò—Å—Ö–æ–¥–Ω—ã–µ –¥–∞–Ω–Ω—ã–µ")# –ø–∞—Ä–∞–º–µ—Ç—Ä 'o' –∑–∞–¥–∞–µ—Ç —Ç–æ—á–µ—á–Ω—ã–π –≥—Ä–∞—Ñ–∏–∫

# –ó–∞–¥–∞–¥–∏–º –Ω–∞–∑–≤–∞–Ω–∏—è –æ—Å–µ–π
plt.xlabel('X')
plt.ylabel('Y')

# –û–ø—Ä–µ–¥–µ–ª—è–µ–º –∞–ø–ø—Ä–æ–∫—Å–∏–º–∏—Ä—É—é—â—É—é –ø—Ä—è–º—É—é
Y_approx = c0 + c1 * X # (—Å–º. –∑–∞–º–µ—Ç–∫—É)
plt.plot(X, Y_approx, '--', label="–ê–ø–ø—Ä–æ–∫—Å–∏–º–∏—Ä—É—é—â–∞—è –ø—Ä—è–º–∞—è")

plt.legend()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 9[0m
[1;32m      6[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mY[39m[38;5;124m'[39m)
[1;32m      8[0m [38;5;66;03m# –û–ø—Ä–µ–¥–µ–ª—è–µ–º –∞–ø–ø—Ä–æ–∫—Å–∏–º–∏—Ä—É—é—â—É—é –ø—Ä—è–º—É—é[39;00m
[0;32m----> 9[0m Y_approx [38;5;241m=[39m c0 [38;5;241m+[39m [43mc1[49m[43m [49m[38;5;241;43m*[39;49m[43m [49m[43mX[49m [38;5;66;03m# (—Å–º. –∑–∞–º–µ—Ç–∫—É)[39;00m
[1;32m     10[0m plt[38;5;241m.[39mplot(X, Y_approx, [38;5;124m'[39m[38;5;124m--[39m[38;5;124m'[39m, label[38;5;241m=[39m[38;5;124m"[39m[38;5;124m–ê–ø–ø—Ä–æ–∫—Å–∏–º–∏—Ä—É—é—â–∞—è –ø—Ä—è–º–∞—è[39m[38;5;124m"[39m)
[1;32m     12[0m plt[38;5;241m.[39mlegend()

[0;31mTypeError[0m: can't multiply sequence by non-int of type 'numpy.float64'

